apt update
# ✓ 1 ;
apt satisfy -y apt
# ✓ 2 ;
apt satisfy -y bash
# ✓ 3 ;
apt satisfy -y bzip2
# ✓ 4 ;
apt satisfy -y ca-certificates
# ✓ 5 ;
apt satisfy -y cmatrix
# ✓ 6 ;
apt satisfy -y command-not-found
# ✓ 7 ;
apt satisfy -y coreutils
# ✓ 8 ;
apt satisfy -y curl
# ✓ 9 ;
apt satisfy -y dash
# ✓ 10 ;
apt satisfy -y debianutils
# ✓ 11 ;
apt satisfy -y dialog
# ✓ 12 ;
apt satisfy -y diffutils
# ✓ 13 ;
apt satisfy -y dos2unix
# ✓ 14 ;
apt satisfy -y dpkg
# ✓ 15 ;
apt satisfy -y ed
# ✓ 16 ;
apt satisfy -y findutils
# ✓ 17 ;
apt satisfy -y game-repo
# ✓ 18 ;
apt satisfy -y gawk
# ✓ 19 ;
apt satisfy -y git
# ✓ 20 ;
apt satisfy -y gpgv
# ✓ 21 ;
apt satisfy -y grep
# ✓ 22 ;
apt satisfy -y gzip
# ✓ 23 ;
apt satisfy -y inetutils
# ✓ 24 ;
apt satisfy -y krb5
# ✓ 25 ;
apt satisfy -y ldns
# ✓ 26 ;
apt satisfy -y less
# ✓ 27 ;
apt satisfy -y libandroid-glob
# ✓ 28 ;
apt satisfy -y libandroid-support
# ✓ 29 ;
apt satisfy -y libassuan
# ✓ 30 ;
apt satisfy -y libbz2
# ✓ 31 ;
apt satisfy -y libc++
# ✓ 32 ;
apt satisfy -y libcrypt
# ✓ 33 ;
apt satisfy -y libcurl
# ✓ 34 ;
apt satisfy -y libdb
# ✓ 35 ;
apt satisfy -y libedit
# ✓ 36 ;
apt satisfy -y libgcrypt
# ✓ 37 ;
apt satisfy -y libgmp
# ✓ 38 ;
apt satisfy -y libgnutls
# ✓ 39 ;
apt satisfy -y libgpg-error
# ✓ 40 ;
apt satisfy -y libiconv
# ✓ 41 ;
apt satisfy -y libidn2
# ✓ 42 ;
apt satisfy -y liblz4
# ✓ 43 ;
apt satisfy -y liblzma
# ✓ 44 ;
apt satisfy -y libmpfr
# ✓ 45 ;
apt satisfy -y libnettle
# ✓ 46 ;
apt satisfy -y libnghttp2
# ✓ 47 ;
apt satisfy -y libnpth
# ✓ 48 ;
apt satisfy -y libresolv-wrapper
# ✓ 49 ;
apt satisfy -y libssh2
# ✓ 50 ;
apt satisfy -y libtirpc
# ✓ 51 ;
apt satisfy -y libunistring
# ✓ 52 ;
apt satisfy -y libuuid
# ✓ 53 ;
apt satisfy -y lsof
# ✓ 54 ;
apt satisfy -y nano
# ✓ 55 ;
apt satisfy -y ncurses
# ✓ 56 ;
apt satisfy -y net-tools
# ✓ 57 ;
apt satisfy -y openssh
# ✓ 58 ;
apt satisfy -y openssl-tool
# ✓ 59 ;
apt satisfy -y openssl
# ✓ 60 ;
apt satisfy -y patch
# ✓ 61 ;
apt satisfy -y pcre2
# ✓ 62 ;
apt satisfy -y pcre
# ✓ 63 ;
apt satisfy -y procps
# ✓ 64 ;
apt satisfy -y psmisc
# ✓ 65 ;
apt satisfy -y readline
# ✓ 66 ;
apt satisfy -y science-repo
# ✓ 67 ;
apt satisfy -y sed
# ✓ 68 ;
apt satisfy -y tar
# ✓ 69 ;
apt satisfy -y termux-am
# ✓ 70 ;
apt satisfy -y termux-auth
# ✓ 71 ;
apt satisfy -y termux-exec
# ✓ 72 ;
apt satisfy -y termux-keyring
# ✓ 73 ;
apt satisfy -y termux-licenses
# ✓ 74 ;
apt satisfy -y termux-tools
# ✓ 75 ;
apt satisfy -y unzip
# ✓ 76 ;
apt satisfy -y util-linux
# ✓ 77 ;
apt satisfy -y wget
# ✓ 78 ;
apt satisfy -y xxhash
# ✓ 79 ;
apt satisfy -y xz-utils
# ✓ 80 ;
apt satisfy -y zlib
# --------------------------
# autoinstall: sh pkglist.sh
# --------------------------
# 丂匚尺丨 卩ㄒ 匚尺乇卂ㄒ乇ᗪ 🇧‌🇾‌🇲‌🇮‌🇸‌🇮
